version: "3.8"
services:
  plytz-runner:
    build:
      context: .
      target: base
    command: uvicorn plytz_runner.main:app --reload --host 0.0.0.0
    ports:
      - 8000:8000
    volumes:
      - .:/plytz
